name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install dependencies
        run: |
          pnpm install
          pnpm i -g wrangler

      - name: Publish
        run: |
          cd packages/dyndns-worker/
          wrangler secret put "CF_EMAIL" "${{secrets.CF_EMAIL}}"
          wrangler secret put "CF_API_TOKEN" "${{secrets.CF_API_TOKEN}}"
          wrangler secret put "SECRET_AUTH_TOKEN" "${{secrets.SECRET_AUTH_TOKEN}}"
          wrangler secret put "SECRET_DYN_DNS_01" "${{secrets.SECRET_DYN_DNS_01}}"
          wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
