name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.4.1
        with:
          version: 7

      - name: Install dependencies
        run: |
          pnpm install
          pnpm i -g wrangler

      - name: Publish
        run: |
          cd packages/dyndns-worker/
          echo ${{secrets.CF_EMAIL}} | wrangler secret put "CF_EMAIL"
          echo ${{secrets.CF_API_TOKEN}} | wrangler secret put "CF_API_TOKEN"
          echo ${{secrets.SECRET_AUTH_TOKEN}} | wrangler secret put "SECRET_AUTH_TOKEN"
          echo ${{secrets.SECRET_DYN_DNS_01}} | wrangler secret put "SECRET_DYN_DNS_01"
          echo ${{secrets.SECRET_DYN_DNS_02}} | wrangler secret put "SECRET_DYN_DNS_02"
          wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
